import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {notFound} from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

interface Params {
  lang: "en-GB";
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: Params;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams(): Params[] {
  return [{ lang: "en-GB" }];
}

export default function RootLayout({
  children,
  params
}: RootLayoutProps) {

  if (params.lang !== "en-GB") notFound();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
